language: node_js
node_js:
  - stable
services:
  - mongodb
script:
  - npm test
  - ./node_modules/.bin/snyk test
  - ./node_modules/.bin/nsp check
  - ./node_modules/.bin/eslint . --ext .jsx, .js
  - ./node_modules/.bin/stylelint ./*/*.css ./*/*/*.css -f verbose
cache:
  directories:
    node_modules