language: node_js
node_js:
  - stable
services:
  - mongodb
script:
  - ./node_modules/.bin/snyk test
  - ./node_modules/.bin/nsp check
  - ./node_modules/.bin/eslint . --ext .jsx, .js
  - ./node_modules/.bin/stylelint ./http/*.css ./http/a/stylesheets/*.css -f verbose
before_install:
  - openssl aes-256-cbc -K $encrypted_c27013234f3c_key -iv $encrypted_c27013234f3c_iv -in Aquaforces-574606712a9b.json.enc -out ~\./Aquaforces-574606712a9b.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: ./Aquaforces-574606712a9b.json.enc
  project: aquaforces-141803
  on: master
cache:
  directories:
    node_modules
