language: node_js
node_js:
  - stable
services:
  - mongodb
script:
  - ./node_modules/.bin/snyk test
  - ./node_modules/.bin/nsp check
  - ./node_modules/.bin/eslint . --ext .jsx, .js
  - ./node_modules/.bin/stylelint ./http/*.css ./http/a/stylesheets/*.css -f verbose
  - ./node_modules/.bin/jest
cache:
  directories:
    node_modules