language: node_js
node_js:
  - stable
services:
  - mongodb
script:
  - npm test
  - ./node_modules/.bin/synk test
  - ./node_modules/.bin/nsp check
  - ./node_modules/.bin/eslint ./
  - ./node_modules/.bin/stylelint ./*/*.css ./*/*/*.css -f verbose
cache:
  directories:
    node_modules