language: node_js
node_js:
  - stable
services:
  - mongodb
install:
  - npm install
  - npm install -g snyk
  - npm install -g nsp
  - npm install -g eslint
  - npm install -g stylelint
  - npm install -g babel-eslint
script:
  - npm test
  - snyk test
  - nsp check
  - eslint ./
  - stylelint ./*/*.css ./*/*/*.css verbose